title: Abhishek Narula
markdown: kramdown
url: ""
baseurl: "/scotchandsolder.github.io"

# for atom feed
author:
  name: Abhishek Narula
  email: narulaab@msu.edu

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true

  projects:
    output: true
    permalink: /projects/:path/


defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/


exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
